export const googleFonts = [
    "Poppins",
    "Roboto",
    "Open Sans",
    "Lato",
    "Montserrat",
    "Oswald",
    "Raleway",
    "Merriweather",
    "Playfair Display",
    "Nunito",
    "Inter",
    "Rubik",
    "Quicksand",
    "Mukta",
    "Cabin",
    "Bebas Neue",
    "Muli",
    "Noto Sans",
    "Work Sans",
    "PT Sans",
    "Fira Sans",
    "Arimo",
    "Titillium Web",
    "Josefin Sans",
    "Pacifico",
    "Lobster",
    "Abril Fatface",
    "Anton",
    "Bangers",
    "Fredoka",
    "Dancing Script",
    "Caveat",
    "Shadows Into Light",
    "Amatic SC",
    "Orbitron",
    "Russo One",
    "Indie Flower",
    "Baloo 2",
    "Zilla Slab",
];