name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
jobs:
  # Job untuk build, tag, dan push image (untuk PR & Main)
  build-image:
    name: Build & Push Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build the application
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
        run: npm run build

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set image tag
        id: set-image-tag
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "::set-output name=tag::pr-${{ github.event.pull_request.number }}"
          else
            echo "::set-output name=tag::${{ github.sha }}"
          fi

      - name: Build & Push Image
        run: |
          docker build \
            --build-arg NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL }} \
            --build-arg NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }} \
            -t adamramdaniyunus/mini-canva:${{ steps.set-image-tag.outputs.tag }} .
          docker push adamramdaniyunus/mini-canva:${{ steps.set-image-tag.outputs.tag }}

  # Job untuk Preview Deployment (PR)
  preview-deployment:
    name: Preview Deployment
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: build-image
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name mini-canva-cluster --region ${{ secrets.AWS_REGION }}

      - name: Deploy Preview Environment
        run: |
          # Salin file template ke file baru yang unik
          cp deployment/mini-canva.yaml deployment/pr-preview-${{ github.event.pull_request.number }}.yaml

          # Gunakan sed yang lebih spesifik agar tidak menyentuh namespace
          sed -i "s/name: mini-canva/name: mini-canva-pr-${{ github.event.pull_request.number }}/g" deployment/pr-preview-${{ github.event.pull_request.number }}.yaml
          sed -i "s/selector:\n    app: mini-canva/selector:\n    app: mini-canva-pr-${{ github.event.pull_request.number }}/g" deployment/pr-preview-${{ github.event.pull_request.number }}.yaml
          sed -i "s/labels:\n        app: mini-canva/labels:\n        app: mini-canva-pr-${{ github.event.pull_request.number }}/g" deployment/pr-preview-${{ github.event.pull_request.number }}.yaml
          sed -i "s|adamramdaniyunus/mini-canva:latest|adamramdaniyunus/mini-canva:pr-${{ github.event.pull_request.number }}|g" deployment/pr-preview-${{ github.event.pull_request.number }}.yaml
          
          # Terapkan perubahan ke cluster
          kubectl apply -f deployment/pr-preview-${{ github.event.pull_request.number }}.yaml

      - name: Get Preview URL and Comment on PR
        id: get-url
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.issue.number;
            let url = '';
            for (let i = 0; i < 60; i++) {
              try {
                const service = await github.rest.kubernetes.getService({
                  namespace: 'mini-canva',
                  name: `mini-canva-pr-${prNumber}`,
                });
                if (service.data.status.loadBalancer.ingress && service.data.status.loadBalancer.ingress.length > 0) {
                  url = service.data.status.loadBalancer.ingress[0].hostname || service.data.status.loadBalancer.ingress[0].ip;
                  if (url) break;
                }
              } catch (e) {
                console.error(e);
              }
              await new Promise(r => setTimeout(r, 10000));
            }

            if (url) {
              github.rest.issues.createComment({
                issue_number: prNumber,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `Preview lingkungan Anda tersedia di:\n\n👉 **http://${url}**`
              });
            } else {
              github.rest.issues.createComment({
                issue_number: prNumber,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: "Gagal mendapatkan URL pratinjau. Silakan periksa log job."
              });
            }

      - name: Cleanup Preview Environment
        if: github.event.action == 'closed'
        run: |
          kubectl delete deployment mini-canva-pr-${{ github.event.pull_request.number }} -n mini-canva
          kubectl delete service mini-canva-pr-${{ github.event.pull_request.number }} -n mini-canva

  # Job untuk Deploy ke Production (main)
  deploy-to-prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: build-image
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name mini-canva-cluster --region ${{ secrets.AWS_REGION }}

      - name: Deploy to Kubernetes
        run: |
          sed -i "s/adamramdaniyunus\/mini-canva:latest/adamramdaniyunus\/mini-canva:${{ github.sha }}/g" deployment/mini-canva.yaml
          kubectl apply -f deployment/mini-canva.yaml
